### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by christianbiring1** [jasonfelice/To-Do-list#4]
### Good job so far... :100: 

> The layout has a good looking
> The user can add, remove tasks
> webpack was set correctly.

But there are still some issues you need to work on.

- [x]  The main container has to be responsive and capable to contain as many tasks as possible the user might add.
- [x] It will be great to not allow the user to add an empty task.

**Comment by jasonfelice** [comment]
Thanks for your time. I have fixed these issues now. :)
