### ISSUE TITLE
Morning session review 10/05/2022

### ISSUE THREAD

**Issue by EidHachem** [jasonfelice/To-Do-list#8]
Hello @jasonfelice, great job implementing the Todo app. The project delivers nice UX, here are some points that could improve the functionality of the project:

-  It could be better to prevent the user from adding empty tasks.
-  It is nice to add the functionality to the refresh button to be able to reload the page.

Happy coding 👏🏽 👏🏽

**Comment by jasonfelice** [comment]
Thank You. I've fixed these issues.
Have a great day :)
